name: cd

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull ogabrielsantoos/backend:service-usuarios
      - name: Stop Docker Container
        run: docker stop usuarios || true
      - name: Remover container
        run: docker rm usuarios || true
      - name: Run Docker Container
        run: docker run --name usuarios -d -p 8080:8080 ogabrielsantoos/backend:service-usuarios

